[package]
name = "libsubconv-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
url = "2.5.0"
